version: '3.4'

services:
  mongoApp:
    container_name: mongoApp
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - "27017:27017"
  forumsservice:
    image: ${DOCKER_REGISTRY-}forumsservice
    build:
      context: .
      dockerfile: ForumsService/Dockerfile
  usersservice:
    image: ${DOCKER_REGISTRY-}usersservice
    build:
      context: .
      dockerfile: UsersService/Dockerfile
